cmake_minimum_required(VERSION 3.16)

project(EJERCICIO_6 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(EJERCICIO_6 main.cpp)

include(GNUInstallDirs)
install(TARGETS EJERCICIO_6
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)
