cmake_minimum_required(VERSION 3.16)

project(EJERCICO_11 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(EJERCICO_11 main.cpp)

include(GNUInstallDirs)
install(TARGETS EJERCICO_11
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)
